// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.flz.nettystudy.protobuf.entity;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flz_nettystudy_protobuf_entity_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flz_nettystudy_protobuf_entity_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\"com.flz.nettystudy.prot" +
      "obuf.entity\"#\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\tB\020B\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_flz_nettystudy_protobuf_entity_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_flz_nettystudy_protobuf_entity_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flz_nettystudy_protobuf_entity_Student_descriptor,
        new String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
