// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.flz.nettystudy.protobuf.entity;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.flz.nettystudy.protobuf.entity.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 数字代表编号，
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
