package com.flz.nettystudy.protobuf.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentMessage.proto


public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 数字代表唯一标签
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * 数字代表唯一标签
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
